Myrottenpotatoes/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => redirect('/movies')
  
  resources :movies do
    resources :reviews
  end
  
  post '/movies/search_tmdb' # Route that posts 'Search TMDb' form
  
  get  'auth/:provider/callback' => 'sessions#create'
  # get '/auth/:provider/callback' => 'sessions#omniauth'
  post 'logout' => 'sessions#destroy'
  get  'auth/failure' => 'sessions#failure'
  get  'auth/google_auth2', :as => 'login'

end

Myrottenpotatoes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Myrottenpotatoes/app/models/movie.rb
class Movie < ActiveRecord::Base
    has_many :reviews
    has_many :moviegoers, :through => :reviews
    before_save :capitalize_title
    
    
    
    def capitalize_title
      self.title = self.title.split(/\s+/).map(&:downcase).
        map(&:capitalize).join(' ')
    end
    
    
    
    def self.all_ratings ; %w[G PG PG-13 R NC-17] ; end #  shortcut: array of strings
    validates :title, :presence => true
    validates :release_date, :presence => true
    validate :released_1930_or_later # uses custom validator below
    validates :rating, :inclusion => {:in => Movie.all_ratings},
        :unless => :grandfathered?
    
    
    
    def released_1930_or_later
        errors.add(:release_date, 'must be 1930 or later') if
        release_date && release_date < Date.parse('1 Jan 1930')
    end
    
    
    
    @@grandfathered_date = Date.parse('1 Nov 1968')
    def grandfathered?
        release_date && release_date < @@grandfathered_date
    end
end

Myrottenpotatoes/app/models/moviegoer.rb
class Moviegoer < ActiveRecord::Base
  has_many :reviews
  has_many :movies, :through => :reviews
  def self.create_with_omniauth(auth)
    Moviegoer.create!(
      :provider => auth["provider"],
      :uid => auth["uid"],
      :name => auth["info"]["name"])
  end
end

Myrottenpotatoes/app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :movie
    belongs_to :moviegoer

    attr_reader :moviegoer_id 
    # review is valid only if it's associated with a movie:
    validates :movie_id, :presence => true

    def self.all_ratings ; %w[1 2 3 4 5] ; end

    # can ALSO require that the referenced movie itself be valid
    #  in order for the review to be valid:
    validates_associated :movie
  end

Myrottenpotatoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  protected 
  def set_current_user
    
    @current_user ||= Moviegoer.find_by(id: session[:user_id])
    begin
    @moviegoer_reviews = @current_user.reviews.find_by(movie_id: params[:movie_id])
    rescue
    end
  end

end

Myrottenpotatoes/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :has_moviegoer_and_movie, :except => [:index, :show]

    def has_moviegoer_and_movie
        unless @current_user
          flash[:warning] = 'You must be logged in.'
          redirect_to movies_path
        end
    end

    def index
      @movies = Movie.all.sort_by { |name| name.title}
    end

    def show
        id = params[:id]
        begin
            @movie = Movie.find(id)
        rescue 
            flash[:notice] = "No movie with the given ID could be found."
            redirect_to movies_path
        end
        
    end

    def new
        @movie = Movie.new
    end 



    def create
        params.require(:movie)
        permitted = params[:movie].permit(:title,:rating,:release_date,:description)
        @movie = Movie.new(permitted)
        if @movie.save
            flash[:notice] = "#{@movie.title} was successfully created."
            redirect_to movies_path
        else
            render 'new'
        end
    end

    def edit
        @movie = Movie.find params[:id]
    end

    def update
        @movie = Movie.find params[:id]
        permitted = params[:movie].permit(:title,:rating,:release_date,:description)
        if @movie.update(permitted)
            flash[:notice] = "#{@movie.title} was successfully updated."
            redirect_to movie_path(@movie)
        else
            render 'edit'
        end
    end

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy
        flash[:notice] = "Movie '#{@movie.title}' deleted."
        redirect_to movies_path
    end

	def search_tmdb
	  # hardwire to simulate failure
	  flash[:warning] = "'#{params[:search_terms]}' was not found in TMDb."
	  redirect_to movies_path
	end
	
end

Myrottenpotatoes/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :has_moviegoer_and_movie, :except => [:index]
    protected
    
    
    def has_moviegoer_and_movie
      unless @current_user
        flash[:warning] = 'You must be logged in to create a review.'
        redirect_to movies_path
      end

      unless (@movie = Movie.find(params[:movie_id]))
        flash[:warning] = 'Review must be for an existing movie.'
        redirect_to movies_path
      end
    end
    
    public
    
    def index
      @movie = Movie.find params[:movie_id]
      @moviegoer = Moviegoer.all
    end

    def new
        @review = @movie.reviews.build
    end
    
    def create
        permitted = params[:review].permit(:potatoes, :comments, :moviegoer_id, :movie_id)
        @review = @movie.reviews.build(permitted)
        @current_user.reviews << @review
        if @review.save
			    flash[:notice] = 'Review successfully create.'
			    redirect_to movie_path(@movie)
		    else
			    render :action => 'new'
		    end
    end
     

     def edit
		    @movie = Movie.find params[:movie_id]
     end

     def update
		    @movie = Movie.find(params[:movie_id])
		    permitted = params[:review].permit(:potatoes, :comments, :moviegoer_id, :movie_id)
		    @review = @movie.reviews.update(permitted)
        if @review
			    flash[:notice] = 'Review successfully update.'
			    redirect_to movie_review_path(@movie)
		    else
			    render  'edit'
		    end
    end
     
    def show
        id = params[:movie_id]
        begin
            @movie = Movie.find(id)
        rescue 
            flash[:notice] = "No movie with the given ID could be found."
            redirect_to movie_path
        end
    end
end

Myrottenpotatoes/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :set_current_user
    def create
      user=Moviegoer.where(:provider => auth["provider"], :uid => auth["uid"]).first ||
        Moviegoer.create_with_omniauth(auth)
      session[:user_id] = user.id
      redirect_to movies_path
    end
    def destroy
      session.delete(:user_id)
      flash[:notice] = 'Logged out from session.'
      redirect_to movies_path
    end
    private
    def auth
        request.env['omniauth.auth']
    end
  end

Myrottenpotatoes/app/helpers/application_helper.rb
module ApplicationHelper
end

Myrottenpotatoes/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RottenPotatoes!
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'
    = csrf_meta_tags

  %body
    %h1
      = render :partial => 'movies/login_form'
    %h3#banner
      = link_to 'RottenPotatoes', movies_path
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    #main
      = yield

    
    

Myrottenpotatoes/app/views/movies/_login_form.html.haml
#login
  - if @current_user
    %p.welcome  Welcome, #{@current_user.name}!
    = link_to 'Log Out', logout_path, :method => :destroy 
  - else
    %p.login= link_to "Log In with Google", "/auth/google_oauth2", method: :post

Myrottenpotatoes/app/views/movies/_movie.html.haml
%tr
    %td= index
    %td= movie.title 
    %td= movie.rating
    %td= movie.release_date
    %td= link_to "More about #{movie.title}", movie_path(movie)

Myrottenpotatoes/app/views/movies/_movie_form.html.haml
- unless @movie.errors.empty?
  #warning
    Errors prevented this movie from being #{controller.action_name}d:
    %ul
      - @movie.errors.full_messages.each do |error|
        %li= error
        
= label :movie, :title, 'Title'
= text_field :movie, 'title'

= label :movie, :rating, 'Rating'
= select :movie, :rating, Movie.all_ratings

= label :movie, :release_date, 'Released On'
= date_select :movie, :release_date, start_year: 1930

= label :movie, :description, 'Description'
= text_area :movie, :description, size: "27x7"

Myrottenpotatoes/app/views/movies/edit.html.haml
%h2 Edit Movie

= form_tag movie_path(@movie), :method => :put do

  = render :partial => 'movie_form'
  
  %h3
  = submit_tag 'Save Changes'
%h3
= link_to 'Cancel' , movie_path(@movie)

 

Myrottenpotatoes/app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

%table#movies
  %thead
    %tr
      %th Number
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each.with_index(1) do |movie, index|
      = render :partial=>'movie', :locals => {:movie => movie , :index => index} 
      -# https://stackoverflow.com/questions/6672454/passing-parameters-to-partial-view

= link_to 'Add new movie', new_movie_path



-# add to end of app/views/movies/index.html.haml:
%h1 Search TMDb for a movie

= form_tag :action => 'search_tmdb' do

  %label{:for => 'search_terms'} Search Terms
  = text_field_tag 'search_terms'
  = submit_tag 'Search TMDb'

Myrottenpotatoes/app/views/movies/new.html.haml
%h2 Create New Movie

= form_tag movies_path, :method => :post do

  = render :partial => 'movie_form'
  
  %h3
  = submit_tag 'Save Changes'
%h3
= link_to 'Cancel' , movies_path

Myrottenpotatoes/app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:
%p#description= @movie.description

= link_to 'Edit info', edit_movie_path(@movie)
%div

= link_to 'Show All Review', movie_reviews_path(@movie)
%div

= link_to 'Back to movie list', movies_path
%div

= link_to 'Delete', movie_path(@movie), :method => :delete
%div

Myrottenpotatoes/app/views/reviews/_movie_review_form.html.haml
= label :review, :potatoes, 'How many potatoes:'
= select :review, :potatoes, Review.all_ratings

= label :review, :comments, 'Comment'
= text_area :review, :comments, size: "27x7"

Myrottenpotatoes/app/views/reviews/edit.html.haml
%h2 Update Review for #{@movie.title}

= form_tag movie_review_path(@movie), :method => :put do
  
  = render :partial => 'movie_review_form'
  
  %h3
  = submit_tag 'Update Review'
%h3
= link_to 'Cancel' , movie_review_path(@movie)

Myrottenpotatoes/app/views/reviews/index.html.haml
%h2 All Review #{@movie.title}






-if @moviegoer_reviews
  = link_to 'Show Review', movie_review_path(@movie, :id)
-else
  = link_to 'Add Review', new_movie_review_path(@movie)
%div
= link_to 'Back to Movie Details', movie_path(@movie)

Myrottenpotatoes/app/views/reviews/new.html.haml
%h1 New Review for #{@movie.title}

= form_tag movie_reviews_path(@movie) do

  = render :partial => 'movie_review_form'
  
  %h3
  = submit_tag 'Create Review'
%h3
= link_to 'Cancel' , movie_path(@movie)

Myrottenpotatoes/app/views/reviews/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Review about #{@movie.title}

%h3 Potatoes: #{@moviegoer_reviews.potatoes}
%h3 Comment:
%p#:comments=@moviegoer_reviews.comments

= link_to 'Edit Review', edit_movie_review_path(@movie)
%div

= link_to 'Back to All reviews movie', movie_reviews_path(@movie)